# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  bos_ak: b89add7b3d9442d397ec0fff3bd17f6a
  bos_sk: 3320129b0b744da89b3cc9d2efda4248
  dmc_media: 'dmc-media-pro'
  dmc_ro: 'dmc-ro-pro'
  media_url: 'http://dmc-media-pro.bj.bcebos.com'  #开发环境存放音频文件
  ro_url: 'http://dmc-media-pro.bj.bcebos.com'     #开发环境存放图片和歌词文件

development:
  <<: *default
  secret_key_base: d57ab110eff68cd3d18b045e640e15bb098ee8c6556a01adf40bb4068f64d8fa5732c5ab5d694850be3dd0077efd9c3b21b12955ad8b844389641bb43ad2875d

test:
  <<: *default
  secret_key_base: e14dc7e16b998202467c309e605d090a73377a07719e0db392125dc8e87fd438d7294ca8e76243c183a9209baf5ab73a560957c27be812ba7aca2a647615bfb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
   dmc_media: ' dmc-media-prod'
  dmc_ro: 'dmc-ro-prod'
  media_url: 'http://dmc-media-prod.bj.bcebos.com'
    ro_url:  'http://dmc-ro-prod.bj.bcebos.com'
