default: &default
  donkey_index: 'donkey_dev'
  analysis_error_type: 'analysis_error'
  analysis_success_type: 'analysis_result'
  analysis_info_type: 'analysis_info'

development:
  <<: *default
  elasticsearch_server: '54.223.52.77:9200'

production:
  <<: *default
  elasticsearch_server: '54.223.52.77:9200'
  donkey_index: 'donkey'

test:
  <<: *default
