default: &default
  elasticsearch_server: '127.0.0.1:9200'
  donkey_index: 'donkey_dev'
  analysis_error_type: 'analysis_error'
  analysis_success_type: 'analysis_result'
  analysis_info_type: 'analysis_info'
  distribution_type: 'distributions'
  remote_servers: ['127.0.0.1','54.223.86.5','54.223.222.214']
  upload_category:
    cp_settlement: 'settlement'
    sp_revenues: 'revenues'

development:
  <<: *default
  elasticsearch_server: '54.222.151.166:9200'
  remote_servers: ['127.0.0.1','54.223.86.5','54.223.222.214']

production:
  <<: *default
  donkey_index: 'donkey'

test:
  <<: *default
